MSG_ADICIONA_USUARIO = 'Adiciona_usuario'
MSG_FAZ_LOGIN = 'Faz_login'
MSG_LISTA_LEILOES = 'Lista_leiloes'
MSG_LISTAGEM = 'Listagem'
MSG_LANCA_PRODUTO = 'Lanca_produto'
MSG_ENTRAR_LEILAO = 'Entrar_leilao'
MSG_ENVIAR_LANCE = 'Enviar_lance'
